/*
 * Copyright 2024 Cedric Hammes
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.cacheoverflow.kbindgen.generator.models

object FileModel {
    fun generateKotlinNativeDefinitionFile(fileName: String, packageString: String, functions: List<FunctionModel>): String {
        val fileBuilder = StringBuilder()
        fileBuilder
            .append("/**\n")
            .append(" * This file was auto-generated by Kbindgen\n")
            .append(" * Developed by Cach30verfl0w\n")
            .append(" */\n\n")
            .append("package $packageString\n\n")
            .append("import de.cacheoverflow.kbindgen.runtime.SharedLibrary\n")
            .append("import kotlinx.cinterop.*\n\n")
        functions.forEach { fileBuilder.append(it.generateKotlinNativeTypeAlias()).append("\n") }
        fileBuilder
            .append("\nvalue class ${fileName}Functions(private val library: SharedLibrary) {\n")
        functions.forEach { fileBuilder.append("    ").append(it.generateFunctionField()).append("\n") }
        fileBuilder.append("}\n")
        
        return fileBuilder.toString()
    }
}
